language: cpp

# from http://stackoverflow.com/a/32127147/266378
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'valgrind']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6', 'valgrind']
      env: COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'valgrind']
      env: COMPILER=clang++-3.7

   - os: osx
     compiler: clang
     env: COMPILER=clang
     before_install:
       - brew update
       - brew install valgrind

script:
  - make